In [226]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import time
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

Brand = []
uniqueid = []
Car_Availability = []
Range = []
Efficiency = []
Weight = []

speed_0_100 = []
Battery = []
fast_charge = []
Towing = []
Cargo_Vol = []
Price_Range = []

Germany_Price = []
Netherlands_Price = []
United_Kingdom_Price = []

Charging_capability = []
Seats = []
Safety_Rating = []

for page in range(0, 10):

    start_time = time.time()

    URL = f"https://ev-database.org/#group=vehicle-group&rs-pr=10000_100000&rs-er=0_1000&rs-ld=0_1000&rs-ac=2_23&rs-dcfc=0_400&rs-ub=10_200&rs-tw=0_3000&rs-ef=100_350&rs-sa=-1_5&rs-w=1000_3500&rs-c=0_5000&rs-y=2010_2030&s=1&p={page}"
    
    response = requests.get(URL)
    soup = BeautifulSoup(response.text, "html.parser")

    for car in soup.find_all('div', class_='item-data'):

        tag = car.find('a', class_='title')

        if tag and tag.has_attr('href'):
            href = tag['href']
            Brand.append(href.split('/')[-1].split('-')[0])
            uniqueid.append(href)
        else:
            Brand.append(np.nan)
            uniqueid.append(np.nan)

        if car.find('span', class_='erange_real'):
            Range.append(car.find('span', class_='erange_real').text.strip())
        else:
            Range.append(np.nan)

        if car.find('span', class_='efficiency'):
            Efficiency.append(car.find('span', class_='efficiency').text.strip())
        else:
            Efficiency.append(np.nan)

        if car.find('span', class_='acceleration_p'):
            speed_0_100.append(car.find('span', class_='acceleration_p').text.strip())
        else:
            speed_0_100.append(np.nan)

        if car.find('span', class_='battery_p'):
            Battery.append(car.find('span', class_='battery_p').text.strip())
        else:
            Battery.append(np.nan)

        if car.find('span', class_='fastcharge_speed_print'):
            fast_charge.append(car.find('span', class_='fastcharge_speed_print').text.strip())
        else:
            fast_charge.append(np.nan)

        if car.find('span', class_='cargo'):
            Cargo_Vol.append(car.find('span', class_='cargo').text.strip())
        else:
            Cargo_Vol.append(np.nan)

        if car.find('span', class_='priceperrange_p'):
            Price_Range.append(car.find('span', class_='priceperrange_p').text.strip())
        else:
            Price_Range.append(np.nan)

        if car.find('span', class_='country_de'):
            Germany_Price.append(car.find('span', class_='country_de').text.strip())
        else:
            Germany_Price.append(np.nan)

        if car.find('span', attrs={'data-tooltip': 'Market Segment'}):
            Charging_capability.append(
                car.find('span', attrs={'data-tooltip': 'Market Segment'}).text.strip()
            )
        else:
            Charging_capability.append(np.nan)
            
    print(f"Page {page + 1} scraped in {round(time.time() - start_time, 2)} seconds")


df = pd.DataFrame({
    "Brand": Brand,
    "UniqueID": uniqueid,
    "Range": Range,
    "Efficiency": Efficiency,
    "0-100": speed_0_100,
    "Battery": Battery,
    "FastCharge": fast_charge,
    "Cargo": Cargo_Vol,
    "Price_per_Range": Price_Range,
    "Germany_Price": Germany_Price,
    "Segment": Charging_capability,

})

print("\nTotal Rows:", len(df))
df

Page 1 scraped in 7.2 seconds
Page 2 scraped in 6.35 seconds
Page 3 scraped in 7.34 seconds
Page 4 scraped in 6.36 seconds
Page 5 scraped in 7.0 seconds
Page 6 scraped in 7.05 seconds
Page 7 scraped in 7.82 seconds
Page 8 scraped in 6.98 seconds
Page 9 scraped in 6.95 seconds
Page 10 scraped in 7.61 seconds

Total Rows: 12330

,Brand,UniqueID,Range,Efficiency,0-100,Battery,FastCharge,Cargo,Price_per_Range,Germany_Price,Segment
0,BMW,/car/3290/BMW-iX3-50-xDrive,610 km,178 Wh/km,4.9 sec,108.7 kWh,230 kW,578 L,€114 /km,"€70,900",D
1,MG,/car/1708/MG-MG4-Electric-64-kWh,360 km,171 Wh/km,7.9 sec,61.7 kWh,107 kW,363 L,€103 /km,"€39,990",C
2,Tesla,/car/3403/Tesla-Model-3-RWD,445 km,135 Wh/km,6.2 sec,60.0 kWh,110 kW,682 L,€89 /km,"€37,970",D
3,BMW,/car/1472/BMW-iX-xDrive40,360 km,197 Wh/km,6.1 sec,71.0 kWh,92 kW,500 L,€225 /km,"€77,300",E
4,Mercedes,/car/3139/Mercedes-Benz-CLA-250plus,585 km,145 Wh/km,6.7 sec,85.0 kWh,208 kW,506 L,€92 /km,"€55,728",D
...,...,...,...,...,...,...,...,...,...,...,...
12325,Porsche,/car/1931/Porsche-Taycan-Turbo-Cross-Turismo,425 km,197 Wh/km,3.3 sec,83.7 kWh,200 kW,489 L,€380 /km,"€165,848",F
12326,Opel,/car/1345/Opel-Zafira-e-Life-S-50-kWh,185 km,250 Wh/km,12.1 sec,46.3 kWh,74 kW,unknown,€306 /km,"€56,700",N
12327,Ford,/car/3164/Ford-e-Tourneo-Custom-L2-160-kW,235 km,272 Wh/km,9.0 sec,64.0 kWh,105 kW,819 L,€295 /km,"€67,771",N
12328,Citroen,/car/1340/Citroen-e-SpaceTourer-XS-50-kWh,185 km,250 Wh/km,12.1 sec,46.3 kWh,74 kW,140 L,€275 /km,"€50,880",N
12329,Peugeot,/car/1350/Peugeot-e-Traveller-Compact-50-kWh,185 km,250 Wh/km,12.1 sec,46.3 kWh,74 kW,unknown,€275 /km,"€50,880",N

In [251]:
df = df.rename(columns={
    "Range": "Range (Km)",
    "Efficiency": "Efficiency (Wh/km)",
    "Weight": "Weight (kg)",
    "0-100": "Acceleration (0-100)",
    "Battery": "Battery (kWh)",
    "FastCharge": "FastCharge (kW)",
    "Towing": "Towing (kg)",
    "Cargo": "Cargo (L)",
    "Price_per_Range": "Price_per_Range (/km)",
    "Germany_Price" : "Germany_Price(€)"
})

In [252]:
import re

df["UniqueID"] = df["UniqueID"].astype('str').str.extract(r"(\d+)").astype('int')

In [253]:
df["Range (Km)"] = df["Range (Km)"].astype('str').str.extract(r"(\d+)").astype('int')

In [254]:
df["Efficiency (Wh/km)"] = df["Efficiency (Wh/km)"].astype('str').str.extract(r"(\d+)").astype('int')

In [255]:
df["Acceleration (0-100)"] = (
    df["Acceleration (0-100)"]
    .astype(str)
    .str.extract(r"(\d+\.?\d*)")
    .astype(float)
)

In [256]:
df["Battery (kWh)"] = (
    df["Battery (kWh)"]
    .astype(str)
    .str.extract(r"(\d+\.?\d*)")
    .astype(float)
)

In [257]:
df["FastCharge (kW)"] = (
    df["FastCharge (kW)"]
    .astype(str)
    .str.extract(r"(\d+)")
    .astype(float)
)

In [258]:
df["Cargo (L)"] = (
    df["Cargo (L)"]
    .astype(str)
    .str.extract(r"(\d+)")
    .astype(float)
)

In [273]:

df["Germany_Price(€)"] = (
    df["Germany_Price(€)"].astype(str)
    .str.extract(r"(\d[\d,]*)")[0]
    .str.replace(",", "", regex=False)
    .astype(float)
)

In [274]:
segment_mapping = {
    "A": "A - Mini",
    "B": "B - Compact",
    "C": "C - Medium",
    "D": "D - Large",
    "E": "E - Executive",
    "F": "F - Luxury",
    "N": "N - Passenger Van",
    "S": "S - Sports"
}

df["Segment"] = (
    df["Segment"]
    .astype(str)
    .str.strip()
    .str[0]              # Take first letter (A/B/C/D/E/F/N/S)
    .map(segment_mapping)
)

In [275]:
df["Price_per_Range (/km)"] = (
    df["Price_per_Range (/km)"]
    .astype(str)
    .str.replace("€", "", regex=False)
    .str.replace("/km", "", regex=False)
    .str.strip()
    .astype(float)
)

In [276]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Brand                  12330 non-null  object
 1   UniqueID               12330 non-null  int64
 2   Range (Km)             12330 non-null  int64
 3   Efficiency (Wh/km)     12330 non-null  int64
 4   Acceleration (0-100)   12330 non-null  float64
 5   Battery (kWh)          12330 non-null  float64
 6   FastCharge (kW)        12330 non-null  float64
 7   Cargo (L)              12060 non-null  float64
 8   Price_per_Range (/km)  12330 non-null  float64
 9   Germany_Price(€)       11420 non-null  float64
 10  Segment                12330 non-null  object
dtypes: float64(6), int64(3), object(2)
memory usage: 1.0+ MB

In [277]:
df.to_csv("EV_Market_Analysis.csv",index = False)

# Raw_Data

In [278]:
df

,Brand,UniqueID,Range (Km),Efficiency (Wh/km),Acceleration (0-100),Battery (kWh),FastCharge (kW),Cargo (L),Price_per_Range (/km),Germany_Price(€),Segment
0,BMW,3290,610,178,4.9,108.7,230.0,578.0,114.0,70900.0,D - Large
1,MG,1708,360,171,7.9,61.7,107.0,363.0,103.0,39990.0,C - Medium
2,Tesla,3403,445,135,6.2,60.0,110.0,682.0,89.0,37970.0,D - Large
3,BMW,1472,360,197,6.1,71.0,92.0,500.0,225.0,77300.0,E - Executive
4,Mercedes,3139,585,145,6.7,85.0,208.0,506.0,92.0,55728.0,D - Large
...,...,...,...,...,...,...,...,...,...,...,...
12325,Porsche,1931,425,197,3.3,83.7,200.0,489.0,380.0,165848.0,F - Luxury
12326,Opel,1345,185,250,12.1,46.3,74.0,NaN,306.0,56700.0,N - Passenger Van
12327,Ford,3164,235,272,9.0,64.0,105.0,819.0,295.0,67771.0,N - Passenger Van
12328,Citroen,1340,185,250,12.1,46.3,74.0,140.0,275.0,50880.0,N - Passenger Van
12329,Peugeot,1350,185,250,12.1,46.3,74.0,NaN,275.0,50880.0,N - Passenger Van